---
- name: Install and start package
  hosts: webservers

  tasks:
    - name: install  Nginx
      homebrew:
        name: nginx
        state: present
    - name: Starting the nginx service
      shell: brew services start nginx
